// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSrTIMWnxsOjTThUL5Ei4lUq1NmyLhXSE',
    appId: '1:1021519029917:web:95b5eb630567f5d9879674',
    messagingSenderId: '1021519029917',
    projectId: 'awamer-3ee7b',
    authDomain: 'awamer-3ee7b.firebaseapp.com',
    storageBucket: 'awamer-3ee7b.firebasestorage.app',
    measurementId: 'G-30M09EFPK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLLvpRCqEgVtnMpxYjHgnpHw8cyvaaSR8',
    appId: '1:1021519029917:android:2e04ba74020861aa879674',
    messagingSenderId: '1021519029917',
    projectId: 'awamer-3ee7b',
    storageBucket: 'awamer-3ee7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAipISJioYavsG1p2lAFo5rHF5OUxdF3Xo',
    appId: '1:1021519029917:ios:caa40f5e4f6475ca879674',
    messagingSenderId: '1021519029917',
    projectId: 'awamer-3ee7b',
    storageBucket: 'awamer-3ee7b.firebasestorage.app',
    iosBundleId: 'com.example.awamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAipISJioYavsG1p2lAFo5rHF5OUxdF3Xo',
    appId: '1:1021519029917:ios:caa40f5e4f6475ca879674',
    messagingSenderId: '1021519029917',
    projectId: 'awamer-3ee7b',
    storageBucket: 'awamer-3ee7b.firebasestorage.app',
    iosBundleId: 'com.example.awamer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSrTIMWnxsOjTThUL5Ei4lUq1NmyLhXSE',
    appId: '1:1021519029917:web:ac2a3e5b387d7224879674',
    messagingSenderId: '1021519029917',
    projectId: 'awamer-3ee7b',
    authDomain: 'awamer-3ee7b.firebaseapp.com',
    storageBucket: 'awamer-3ee7b.firebasestorage.app',
    measurementId: 'G-41YLF17Z7Z',
  );
}
